apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: contract-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: contract-git
  params:
    - name: pathToYamlFile
      value: "knative/service.yaml"
    - name: imageUrl
      value: docker.io/daisyycguo/contract
    - name: imageTag
      value: "1.0"
  trigger:
    type: manual
  serviceAccount: pipeline-account