apiVersion: v1
kind: ServiceAccount
metadata:
  name: route-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-sa-watcher
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - routes
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: route-sa-event-watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: route-sa-watcher
subjects:
  - kind: ServiceAccount
    name: route-sa
    namespace: default